### ISSUE TITLE
load_data(), doesn't load all classes

### ISSUE THREAD

**Issue by Luucky** [hendrycks/error-detection#1]
Hey guys,

I was just reviewing your code to understand it and try to implement it into my own deep learning classifier, to be able to detect unseen samples that are out-of-distribution and I have noticed that you are making a mistake in your `load_data()` method. 

```
    x, y = [], []
    with open(filename, "r") as f:
        for line in f:
            line = re.sub(r'\W+', ' ', line).strip()
            x.append(line[1:])
            x[-1] = ' '.join(word for word in x[-1].split() if word not in stop_words)
            **y.append(line[0])**
    return x, np.array(y, dtype=int)
```

The bold line takes only the first digit of the class and it seems that for classes above 9, it needs to be line[:1] otherwise, only the first digit is extracted. I am wondering if that would affect the results of your scripts.

Also, I've been having a little trouble with implementing your solution into my project as I don't really know which statistics I should use for out-of-distribution detection. If you could point me in the right direction I would appreciate it. Thanks!
[20Newsgroups.ipynb](https://github.com/hendrycks/error-detection/blob/master/NLP/Categorization/20%20Newsgroups.ipynb)

**Comment by hendrycks** [comment]
We no longer use this 20 Newsgroups code, but there is more actively maintained 20 Newsgroups code here: https://github.com/hendrycks/outlier-exposure/tree/master/NLP_classification

**Comment by Luucky** [comment]
Thanks for the link. I am wondering are you on any slack channels? Where is best to contact you in regards to your implementation? I have a couple of questions about how I could use this method in my own project.

**Comment by hendrycks** [comment]
My email is shown at https://github.com/hendrycks

**Comment by Luucky** [comment]
Great I have shot you an email already!

**Comment by hendrycks** [comment]
I don't see it.

**Comment by Luucky** [comment]
Sent now, my email program chocked up and didn't let out the email. Apologies!
